version: "3"
x-config:
  &default-config
  image: chromeless-pytest
  volumes:
    - ../chromeless:/local/chromeless
  environment:
    - CHROMELESS_SERVER_FUNCTION_NAME=${CHROMELESS_SERVER_FUNCTION_NAME}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_DEFAULT_REGION=${AWS_REGION}
    - API_URL=${API_URL}
    - API_KEY=${API_KEY}

services:
  pytest_latest:
    << : *default-config
    working_dir: /latest

  pytest_029:
    << : *default-config
    working_dir: /0.2.9

  pytest_030:
    << : *default-config
    working_dir: /0.3.0

  pytest_036:
    << : *default-config
    working_dir: /0.3.6

  pytest_047:
    << : *default-config
    working_dir: /0.4.7
